//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyContactBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactId { get; set; }
        public string ContactFName { get; set; }
        public string ContactLName { get; set; }
        public string EmailAddress { get; set; }
        public int ContactNumber1 { get; set; }
        public Nullable<int> ContactNumber2 { get; set; }
        public int CountryId { get; set; }
        public int StateId { get; set; }
        public string ImagePath { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
    }
}
